# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [1]:
import numpy as np

In [3]:
data = np.random.uniform(0, 20, size = (4, 7))
print(data)
(data-np.min(data))/(np.max(data)-np.min(data))

[[ 2.75269124  9.79099087  0.82423688  5.24609716  7.69964897 11.50375848
   3.07336576]
 [11.86700502 11.61940442  5.14535653 12.13725485  2.72722465  6.80580917
   2.88108708]
 [ 4.10817895 12.89926449  5.48369184  8.42556543 16.89142103 11.50959987
  15.44375161]
 [17.53454822 18.20751069 10.18429409 17.11583528 11.89665526 11.28500932
  15.43235677]]


array([[0.11093735, 0.51582654, 0.        , 0.25437442, 0.39551883,
        0.61435617, 0.12938465],
       [0.6352525 , 0.62100889, 0.24857916, 0.65079904, 0.10947235,
        0.3440993 , 0.11832352],
       [0.1889139 , 0.69463484, 0.26804243, 0.43727831, 0.92428989,
        0.61469221, 0.84101044],
       [0.96128678, 1.        , 0.53845192, 0.93719967, 0.63695818,
        0.60177229, 0.84035493]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [3]:
arr = np.random.randint(0, 10, size = (8, 10))
print(arr)
print(np.argmin(np.sum(arr, axis=1)))
arr[np.argmin(np.sum(arr, axis=1))]

[[8 6 4 1 2 4 4 3 9 0]
 [9 6 1 3 5 8 0 8 4 8]
 [7 9 3 6 3 8 8 0 2 2]
 [0 4 8 7 9 5 3 4 1 5]
 [9 6 0 3 9 2 9 9 4 0]
 [7 9 1 9 8 0 3 0 6 2]
 [9 6 0 1 5 7 0 4 9 5]
 [9 7 8 4 4 5 1 8 1 6]]
0


array([8, 6, 4, 1, 2, 4, 4, 3, 9, 0])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [4]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

In [5]:
x = np.random.randint(0, 20, size=5)
y = np.random.randint(0, 20, size=5)
print(x)
print(y)
print(np.linalg.norm(x-y))

sqr = np.square(x-y)
print(np.sqrt(np.sum(sqr)))

[ 2  1 17 18 19]
[15 11 10  9  7]
23.302360395462088
23.302360395462088


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [6]:
a = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
b = np.array([[3, -1], [2, 1]])
c = np.array([[7, 21], [11, 8], [8, 4]])
xy = np.matmul(np.linalg.inv(a), (-c))
print(xy)
xyz = np.matmul(xy, np.linalg.inv(b))
print(xyz)

[[ 3. -1.]
 [-4.  3.]
 [ 1. -7.]]
[[ 1.00000000e+00  1.11022302e-15]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [17]:
data = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows=1, dtype=np.int32)

data[0:5, :]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [18]:
sliced = data[:,1:]
print(np.mean(sliced, axis=0))
print(np.min(sliced, axis=0))
print(np.max(sliced, axis=0))
print(np.median(sliced, axis=0))

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [19]:
print(np.clip(data[:, 1], 0, np.quantile(data[:, 1], 0.75, method='higher')))

[60 25 10 ... 65  5 65]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [20]:
print(np.count_nonzero(data[:, 1] == 0))
np.place(data, data==0, 1)

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [25]:
len(np.unique(sliced, axis=0))

4183

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [26]:
print(np.unique(data[:, 2], axis=0))
print(np.unique(data[:, 2], axis=0).size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [27]:
data[np.where(data[:, 2] <= 5)]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [30]:
print(data[:, 2]/data[:, 1], max(data[:, 2]/data[:, 1]))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ] 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [33]:
np.mean(data[np.argsort(data[:, 1])][::-100][:, 2])

9.016

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [87]:
data[np.random.choice(len(data), 10)]

array([[ 48464,     40,     12],
       [329264,    490,      5],
       [253429,     30,      8],
       [334623,     40,     12],
       [ 43744,    215,     12],
       [386659,     10,      4],
       [374600,    147,     10],
       [445731,     30,     10],
       [146704,    120,     12],
       [ 46332,    510,     21]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [12]:
(len(data[np.where(data[:, 2] < data[:, 2].mean())]) / len(data)) * 100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [28]:
new_array = np.append(data, [[1] if i[1] <= 20 and i[2] <= 5 else [0] for i in data], axis=1)
new_array

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [30]:
(len(new_array[np.where(new_array[:, 3] == 1)]) / len(new_array)) * 100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.